#Embedded file name: /home/django/DegreePlanner/DegreePlanner/settings.py
"""
Django settings for degreeplanner project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

SECRET_KEY = 'i&rp48-p5%#&&7!vcw8h!vp1&w##c^(e#@#$-r(e$#^h&ekk3f'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = ('django.contrib.admin', 
                  'django.contrib.auth', 
                  'django.contrib.contenttypes', 
                  'django.contrib.sessions', 
                  'django.contrib.messages', 
                  'django.contrib.staticfiles', 
                  'planner', 
                  'registration',
                  'pages',)

MIDDLEWARE_CLASSES = ('django.contrib.sessions.middleware.SessionMiddleware', 
                      'django.middleware.common.CommonMiddleware', 
                      'django.middleware.csrf.CsrfViewMiddleware', 
                      'django.contrib.auth.middleware.AuthenticationMiddleware', 
                      'django.contrib.auth.middleware.SessionAuthenticationMiddleware', 
                      'django.contrib.messages.middleware.MessageMiddleware', 
                      'django.middleware.clickjacking.XFrameOptionsMiddleware', 
                      'django.middleware.security.SecurityMiddleware')

ROOT_URLCONF = 'DegreePlanner.urls'

TEMPLATES = [
             {'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [os.path.join(BASE_DIR, 'DegreePlanner/templates')],
  'APP_DIRS': True,
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]

WSGI_APPLICATION = 'DegreePlanner.wsgi.application'

DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'NAME': 'django',
             'USER': 'django',
             'PASSWORD': 'U84S122VxH',
             'HOST': 'localhost',
             'PORT': ''}}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['*']

STATIC_URL = '/static/'

STATIC_ROOT = '/home/django/DegreePlanner/planner/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
LOGIN_REDIRECT_URL = '/planner/'
LOGIN_URL = '/accounts/login/'
